# Creates a VPC with a single CIDR block, an Internet Gateway attached to the
# VPC, a public Route Table with a Route to the Internet Gateway, and two
# private Route Tables.
#
# Parameters:
# - CidrBlockPrefix: The 16-bit prefix for the CIDR block. Valid values are:
#   - 10.0 through 10.255
#   - 172.16 through 172.31
#   - 192.168
#
# Outputs:
# - VpcId: The ID of the VPC that was created.
# - PublicRouteTableId: The ID of the Route Table that was created with a route
#   to the Internet Gateway.
# - PrivateRouteTable1Id: The ID of the first private Route Table that was
#   created.
# - PrivateRouteTable2Id: The ID of the second private Route Table that was
#   created.

Parameters:
  CidrBlockPrefix:
    Type: String
    MinLength: 4
    MaxLength: 7
    AllowedPattern: ^[0-9]{1,3}\.[0-9]{1,3}$

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub ${CidrBlockPrefix}.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: MainVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MainIGW
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: PublicRT
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: PrivateRT1
  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: PrivateRT2

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
  PublicRouteTableId:
    Description: Public route table ID
    Value: !Ref PublicRouteTable
  PrivateRouteTable1Id:
    Description: Private route table ID
    Value: !Ref PrivateRouteTable1
  PrivateRouteTable2Id:
    Description: Private route table ID
    Value: !Ref PrivateRouteTable2
